### ISSUE TITLE
Problem for get_nearest_power_of_two

### ISSUE THREAD

**Issue by deadmanhead1602** [seanharr11/etlalchemy#10]
I try to migrate oracle DB to mysql and find that Datatype VARCHAR2(2 byte) will convert to VARCHAR(1).

The problem due to get_nearest_power_of_two.  2 of power of two should be 4.

Log trace:
ETLAlchemySource (INFO) - (code) VARCHAR
ETLAlchemySource (INFO) - Bases: ['STRING']
ETLAlchemySource (INFO) - Converting to -> VARCHAR(1 (maxsize: 2)

**Comment by seanharr11** [comment]
@deadmanhead1602 - glad you pointed this out, had a major flaw in the logic here if the ``maxsize`` was an even power of 2.

Commit b8b7d3a47c1e7e52d7f0233257fdfa1164f64c98 should fix this, as well as optimize the deduced column size on MySQL for disk-size, memory & caching.

[This stackoverflow answer](http://stackoverflow.com/questions/1962310/importance-of-varchar-length-in-mysql-table#answer-1962329) explains why powers of 2 and minimizing the VARCHAR(n) size matters, specifically on MySQL.

Can you pull the latest changes to your repository, install the package to a local virtualenv, and re-run your test above? This way I can have another set of us eyes verify before packaging this in a release. (I need to build some tests into this repository, I know that's lacking...)

Thanks! And let me know if you have issues trying to install directly from the git repo.

**Comment by seanharr11** [comment]
@deadmanhead1602 did this work for you?
